### ISSUE TITLE
WikidPad not working on Fedora 22

### ISSUE THREAD

**Issue by matysek** [butscher/WikidPad#1]
Hi,

I recently upgraded to Fedora 22 but none of wikidpad versions works and just a rectangular window with the wikidpad icon is shown.

Fedora 22 bundles wxPython 3.0.2.0 gtk3 (classic)

With the latest git version I get this output:

```
$ cat ./WikidPad_Error.log    
Version: 'wikidPad 2.3beta13_01' Session start: 2015-06-20 21:50:15
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
```

Is there anything I could do to get WikidPad working on FC22?

**Comment by ClaudePP** [comment]
Hello, the same experience! Whats going on?! I need it, wikidpad become my memory! :-)

**Comment by matysek** [comment]
@ClaudePP I gave up and just using wikidpad with wine.

**Comment by ClaudePP** [comment]
look at this thread:
http://comments.gmane.org/gmane.comp.python.wikidpad/5587
This version:
https://bitbucket.org/chriz/wikidpad/downloads
works for me.
Shame on developers thou! Official version should work!

**Comment by cknoll** [comment]
> Shame on developers thou! Official version should work!

I think it would be impossible for a small free software project to test on all platforms. Apparently there already exists a bugfix but it is not included in the main repo. So let's contact the author and ask him to send a pull request to this (official) repo.

**Comment by matysek** [comment]
Question is if the original author has more time for wikidpad maintenance. If not then an unofficial repo is probably the way to go.

**Comment by gchriz** [comment]
Hi! I'm the one with the patch for this issue - in my Bitbucket repo - as mentioned by ClaudePP above.
In the meantime I forked Michael's original repo here as well and I'm trying to learn git/github now.
So I hope to being able to provide pull requests soon. But please don't hold your breath...

**Comment by matysek** [comment]
Closing. Please continue with further development and discussion in https://github.com/WikidPad/WikidPad/issues/1
